---
- name: Install .NET SDK and ASP.NET Core Runtime
  ansible.builtin.apt:
    name:
      - aspnetcore-runtime-{{ dotnet_version }}
      - dotnet-sdk-{{ dotnet_version }}
    state: present
    update_cache: true
  become: true
