---
- name: Install apt packages
  ansible.builtin.include_tasks: apt.yml

- name: Create directory for AppImages
  ansible.builtin.include_tasks: appimage.yml

- name: Install snaps
  ansible.builtin.include_tasks: snaps.yml

- name: Include Docker installation
  ansible.builtin.include_tasks: docker.yml

# - name: Kill all user sessions
#   ansible.builtin.meta: reset_connection

- name: Install Node.js
  ansible.builtin.include_tasks: nodejs.yml

- name: Include Neovim installation tasks
  ansible.builtin.include_tasks: neovim.yml

- name: Install Go
  ansible.builtin.include_tasks: go.yml

- name: 'Install C# .NET'
  ansible.builtin.include_tasks: csharp.yml

- name: Install Conda
  ansible.builtin.include_tasks: conda.yml

- name: 'Install LaTeX'
  ansible.builtin.include_tasks: latex.yml

- name: 'Install lazygit'
  ansible.builtin.include_tasks: lazygit.yml

- name: Include NerdFont installation tasks
  ansible.builtin.include_tasks: nerdfonts.yml

- name: Setup bash
  ansible.builtin.include_tasks: bash.yml

# Note that this will create a GUI prompt for the user
# to start Dropbox and log in.
- name: Install Dropbox
  ansible.builtin.include_tasks: dropbox.yml

- name: Install IBKR Trader Workstation
  ansible.builtin.include_tasks: ibkr_tws.yml

- name: Configure UFW
  ansible.builtin.include_tasks: ufw.yml
