---
- name: Setup bash
  ansible.builtin.include_tasks: bash.yml

- name: Include Neovim installation tasks
  ansible.builtin.include_tasks: neovim.yml

- name: Include NerdFont installation tasks
  ansible.builtin.include_tasks: nerdfonts.yml

- name: Include Docker installation
  ansible.builtin.include_tasks: docker.yml

# only useful if using ssh connection
- name: Kill all user sessions
  ansible.builtin.meta: reset_connection

- name: Install snaps
  ansible.builtin.include_tasks: snaps.yml

- name: Install Anaconda
  ansible.builtin.include_tasks: anaconda.yml

- name: Install NodeJS
  ansible.builtin.include_tasks: nodejs.yml

- name: Install Go
  ansible.builtin.include_tasks: go.yml

- name: 'Install C# .NET'
  ansible.builtin.include_tasks: csharp.yml

- name: 'Install LaTeX'
  ansible.builtin.include_tasks: latex.yml

- name: 'Install lazygit'
  ansible.builtin.include_tasks: lazygit.yml
