---
- name: Install Neovim basic utils
  ansible.builtin.apt:
    pkg:
      - git
      - build-essential
      - make
      - unzip
      - ripgrep
      - xclip
  become: true

- name: Install Neovim AppImage #https://github.com/neovim/neovim/blob/master/INSTALL.md
  ansible.builtin.get_url:
    url: "{{ neovim_download_url }}"
    dest: /home/{{ username }}/bin/nvim.appimage
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0774'

- name: Create symbolic link to app image
  ansible.builtin.file:
    src: /home/{{ username }}/bin/nvim.appimage
    dest: /home/{{ username }}/bin/nvim
    state: link
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'

- name: Clone Neovim configuration
  ansible.builtin.git:
    repo: git@github.com:brentjm/Neovim.git
    dest: /home/{{ username }}/.config/nvim


