---
- name: "Create font directory"
  ansible.builtin.file:
    path: /home/{{ username }}/.local/share/fonts
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'

- name: "Download NerdFont(s)"
  ansible.builtin.get_url:
    url: "{{ nerdfonts_download_url }}"
    dest: /home/{{ username }}/.local/share/fonts/Hack.zip
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0664'

- name: Unzip NerdFont
  ansible.builtin.unarchive:
    src: "/home/{{ username }}/.local/share/fonts/Hack.zip"
    dest: "/home/{{ username }}/.local/share/fonts/"
    remote_src: yes
  
- name: Remove Hack.zip file
  ansible.builtin.file:
    path: "/home/{{ username }}/.local/share/fonts/Hack.zip"
    state: absent

- name: Update fonts
  ansible.builtin.shell: fc-cache -f -v

## This downloads all fonts - very large
#- name: "Download NerdFont(s)"
#  ansible.builtin.git:
#    repo: https://github.com/ryanoasis/nerd-fonts.git
#    dest: /home/{{ username }}/Downloads/nerdfonts
#
#- name: "Install NerdFont(s)"
#  ansible.builtin.shell: ./install.sh Hack
#  args:
#    chdir: "/home/{{ username }}/Downloads/nerdfonts"
