---
# https://docs.volta.sh/guide/getting-started
- name: Install Volta
  ansible.builtin.shell: |
    curl {{ volta_download_url }} | bash
  args:
    creates: ~/.volta/bin/volta

- name: Ensure Volta is in PATH
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: 'export PATH=$HOME/.volta/bin:$PATH'
    state: present

- name: Install Node.js using Volta
  ansible.builtin.command:
    cmd: /home/{{ username }}/.volta/bin/volta install node@{{ node_version }}
    creates: ~/.volta/tools/image/node/{{ node_version }}

- name: Install Yarn using Volta
  ansible.builtin.command:
    cmd: /home/{{ username }}/.volta/bin/volta install yarn
    creates: ~/.volta/tools/image/yarn
