---
- name: Install snap applications
  community.general.snap:
    name:
      - inkscape
      - gimp
      - chromium
      - gimp
      - jq
      - obs-studio
      - spotify
      - teams-for-linux
      - youtube-dl
      # - webcamoid
  become: true

- name: Install VSCode
  community.general.snap:
    name: 
      - code
      - blender
    classic: true
  become: true
