---
- name: Configure Ubuntu server
  hosts: home_servers
  gather_facts: true
  become: true
  tasks:
    - name: Entry point for home Ubuntu server configuration
      ansible.builtin.include_role:
        name: server
        tasks_from: main.yml
