---
- name: Pull Portainer image
  community.docker.docker_image:
    name: portainer/portainer-ce
    tag: latest
    source: pull

- name: Create Portainer container
  community.docker.docker_container:
    name: portainer
    image: portainer/portainer-ce:latest
    state: started
    restart_policy: always
    published_ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

- name: Create Portainer data volume
  community.docker.docker_volume:
    name: portainer_data
    state: present

# https://docs.portainer.io/start/requirements-and-prerequisites
- name: Open UFW port 9443
  ansible.builtin.ufw:
    rule: allow
    port: '9443'
    proto: tcp
