---
- name: Allow SSH port
  ufw:
    rule: allow
    name: OpenSSH

- name: Allow TWS ports from Docker network
  ufw:
    rule: allow
    port: 7496:7497
    proto: tcp
    src: 172.0.0.0/8

- name: Enable UFW
  ufw:
    state: enabled
