---
- name: Configure Proxmox server
  hosts: proxmox_servers
  gather_facts: true
  become: true
  tasks:
    - name: Entry point for Proxmox server configuration
      ansible.builtin.include_role:
        name: basic
        tasks_from: main.yml
