---
- name: Create Ansible SSH key pair on control node
  openssh_keypair:
    path: ~/.ssh/id_rsa_ansible
    type: rsa
    size: 4096
    state: present
    passphrase: "{{ vault_ssh_key_passphrase }}"
    force: true
  delegate_to: localhost
  run_once: true
