- name: Backup the proxmoxlib.js file
  ansible.builtin.command: 
    cmd: cp proxmoxlib.js proxmoxlib.js.bak
  args:
    chdir: /usr/share/javascript/proxmox-widget-toolkit/

- name: Change the subscription check to looking for not 'active'
  ansible.builtin.replace:
    path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
    regexp: "toLowerCase\\(\\) !== 'active'"
    replace: "toLowerCase() === 'active'"
